#!/bin/bash

if [ -n "$1" ] && [ -n "$2" ]; then
	url="http://www.mangareader.net"
	comic=$1
	chap=$2
	prefix="curl -s $url/$comic/$chap"
	page_count=$($prefix | grep "</select>" | egrep -o \[0-9\]\+)
	if [ -n "$page_count" ]; then
		mkdir $comic-$chap > /dev/null 2>&1
		for num in $(seq 1 $page_count); do
			pic_link=$($prefix/$num | grep "<a" | grep "src" | egrep -o http://\[A-Za-z0-9./-\]\+.jpg)
			echo -n "downloading $comic-$chap/$comic-$chap-$num.jpg........"
			curl -s -o $comic-$chap/$comic-$chap-$num.jpg  $pic_link
			echo "done!"
		done
		echo "creating a single PDF!"
		cd $comic-$chap
		convert $(ls -1v) $comic-$chap.pdf
		mv $comic-$chap.pdf ../
		cd ../
		echo "All done!"
	fi
fi

exit 0
