#!/bin/bash

if [ -n "$1" ] && [ -n "$2" ]; then
	url="http://www.mangareader.net"
	comic=$1
	chap=$2
	prefix="curl -s $url/$comic/$chap"
	page_count=$($prefix | grep "</select>" | egrep -o \[0-9\]\+)
	if [ -n "$page_count" ]; then
		mkdir $comic-$chap > /dev/null 2>&1
		echo "Totally $page_count Pages in Chapter $chap!"
		for num in $(seq -w 1 $page_count); do
			pic_link=$($prefix/$num | grep "<a" | grep "src" | egrep -o http://\[A-Za-z0-9./-\]\+.jpg)
			echo -n "downloading $comic-$chap/$comic-$chap-$num.jpg........"
			curl -s -o $comic-$chap/$comic-$chap-$num.jpg  $pic_link
			echo "done!"
		done
		echo "Compressing Pictures!!!"
		zip -r $comic-$chap $comic-$chap
		mv $comic-$chap.zip $comic-$chap.cbr
		rm -rf $comic-$chap
		echo "Succefully Downloaded."
	fi
else
	echo "Maybe not released yet!"
fi

exit 0
